export default {
  FETCH_TODOS: "FETCH_TODOS",
  REMOVE_TODO: "REMOVE_TODO",
  ADD_TODO: "ADD_TODO",
  FILTER_TODOS: "FILTER_TODOS",
  EDIT_TODO: "EDIT_TODO",
  START_EDITING: "START_EDITING",
  REMOVE_COMPLETED_TODOS: "REMOVE_COMPLETED_TODOS",
  START_TIMER: "START_TIMER",
  END_TIMER: "END_TIMER",
  FETCH_TIMERS: "FETCH_TIMERS",
  UPDATE_TIMER: "UPDATE_TIMER"
};
